# Generated by Django 5.1.6 on 2025-03-01 15:39

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', django_quill.fields.QuillField(blank=True, null=True)),
                ('full_description', django_quill.fields.QuillField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='/static/images/mts.jpg', null=True, upload_to='media/images/')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('home_page', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('participants_ages', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('pick_up_location', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('included', django_quill.fields.QuillField(blank=True, null=True)),
                ('expected', django_quill.fields.QuillField(blank=True, null=True)),
                ('accessibility', models.CharField(max_length=100)),
                ('additional_info', django_quill.fields.QuillField(blank=True, null=True)),
                ('cancellation_policy', django_quill.fields.QuillField(blank=True, null=True)),
                ('FAQ', django_quill.fields.QuillField(blank=True, null=True)),
                ('image_2', models.ImageField(blank=True, default='/static/images/mts.jpg', null=True, upload_to='media/images/')),
                ('image_3', models.ImageField(blank=True, default='/static/images/mts.jpg', null=True, upload_to='media/images/')),
            ],
        ),
    ]
