# Generated by Django 5.1.6 on 2025-03-12 19:14

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('full_description', django_quill.fields.QuillField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='static/images/female_review.png', null=True, upload_to='media/images/')),
            ],
        ),
    ]
